### PR TITLE
Add CONTRIBUTING.md for prompt submission guidelines ✍️

### LINKED ISSUE #7: Move contributing process to CONTRIBUTING.md
The CONTRIBUTING.md file does not provide enough details about how to actually contribute to this repo, only some guidelines. The actual, repo specific steps are in the README.md under the [Contributing Process](https://github.com/ServiceNowDevProgram/ServiceNow-GenAi-Prompt-Library?tab=readme-ov-file#contributing-process) section.
I suggest moving its contents into the CONTRIBUTING.md file, and linking to it from the existing readme section.

### PR DESCRIPTION
**Pull request by tejasathalye**
## Description

**This update moves the contributing process details to the `CONTRIBUTING.md` file 📑, streamlining the contribution guidelines for the ServiceNow's GenAI Prompt Library. This ensures that all relevant information is centralized, making it easier for contributors to find and follow the submission process. ✍️**

### Fixed #7 !

### CODE REVIEW

**Review by Lacah — APPROVED** [review]

**Comment by Lacah** [comment]
Great stuff, thanks a lot!

**Comment by tejasathalye** [comment]
### hey @Lacah it would be great if you can add the label as hacktoberfest-accepted label to it!
Thanks!

**Comment by SapphicFire** [comment]
> ### hey @Lacah it would be great if you can add the label as hacktoberfest-accepted label to it!
> 
> Thanks!
> 
> 

Merging as done here is sufficient according to the [Maintainer](https://hacktoberfest.com/participation/#maintainers) section of the participation page. Please let us know if you don't see this sync to your profile after a day

**Comment by earlduque** [comment]
Hello! This comment is to inform you that unfortunately, this repository, on October 3, was excluded from participation in the official Hacktoberfest event. As I investigate into why it was excluded, I would like to encourage you to participate in our other Hacktoberfest projects so that you still get completion progress for the official Hacktoberfest event.

We will count this contribution for progress made for ServiceNow rewards (make sure to check out the other eligibility requirements in the blog post), but if you want the rewards from the official event, you will need to make sure you have at least 4 Pull Requests merged into _other_ projects by the end of October. We apologize for the inconvenience and appreciate your participation regardless!

Earl

**Pull request merged**
