### PR TITLE
Prompt for improving interpersonal skills in workplace

### PR DESCRIPTION
**Pull request by ultralegendary**
Hi,
The purpose of this prompt is to provide everyone with a framework for improving your interpersonal skills and fostering positive relationships within the workplace. In order to create a positive workplace and good relationship, it needs to start from us. 
Use this prompt to know what you could have done in order to make the other colleagues feel good and to create a positive environment.

Thanks.

### CODE REVIEW

**Review by Lacah — CHANGES_REQUESTED** [review]
Hi,
This is really cool, but please remove the markdown (.md) extension. The file does not need to have any extension.
As a result, you might want to consider rewriting your prompt, considering that markdown will not be used / rendered.
Thanks!

**Comment by ultralegendary** [comment]
Hi,
I have removed the markdown and updated the file.
Thanks.

**Review by Lacah — APPROVED** [review]

**Comment by Lacah** [comment]
Looks good, thank you!

**Comment by earlduque** [comment]
Hello! This comment is to inform you that unfortunately, this repository, on October 3, was excluded from participation in the official Hacktoberfest event. As I investigate into why it was excluded, I would like to encourage you to participate in our other Hacktoberfest projects so that you still get completion progress for the official Hacktoberfest event.

We will count this contribution for progress made for ServiceNow rewards (make sure to check out the other eligibility requirements in the blog post), but if you want the rewards from the official event, you will need to make sure you have at least 4 Pull Requests merged into _other_ projects by the end of October. We apologize for the inconvenience and appreciate your participation regardless!

Earl

**Pull request merged**
