### PR TITLE
Create Get List of Duplicate Script Include Names

### PR DESCRIPTION
**Pull request by bkb68**
Creates a script that checks Script Include API Names for duplicates, which is technically possible and maddening to troubleshoot when you can't figure out why your script is not running.

### CODE REVIEW

**Comment by niamccash** [comment]
Did you mean to submit this to the [code-snippets repository](https://github.com/ServiceNowDevProgram/code-snippets)? 

This repo is for generative AI prompts.

**Comment by bkb68** [comment]
I included the code with now assist prompt that I used to generate a
script.

**Comment by niamccash** [comment]
Was the prompt you used _**print a list of Script Include Names that are duplicated**_?
The prompt should be included in your submitted file.

**Comment by bkb68** [comment]
Yes, I thought I put that at the beginning of the submitted file named Get
List of Duplicate Script Include Names, then I showed the result which I
thought is what was done in the example I looked at, but total newbie here.

**Comment by niamccash** [comment]
Yes, that prompt is there. I just wasn't sure about it because it wasn't ServiceNow specific and when I ran it through Copilot, it didn't give the code you provided/didn't give ServiceNow specific code. But when put through Now Assist code generation, it does produce the right output. 

Would it be ok if I updated the file you submitted a little and labeled the prompt with the word "prompt" and the code with the label "Example output"?

**Comment by bkb68** [comment]
Sounds like a good improvement.

**Comment by niamccash** [comment]
Thanks! And thank you for the contribution!

**Comment by earlduque** [comment]
Hello! This comment is to inform you that unfortunately, this repository, on October 3, was excluded from participation in the official Hacktoberfest event. As I investigate into why it was excluded, I would like to encourage you to participate in our other Hacktoberfest projects so that you still get completion progress for the official Hacktoberfest event.

We will count this contribution for progress made for ServiceNow rewards (make sure to check out the other eligibility requirements in the blog post), but if you want the rewards from the official event, you will need to make sure you have at least 4 Pull Requests merged into _other_ projects by the end of October. We apologize for the inconvenience and appreciate your participation regardless!

Earl

**Pull request merged**
