### PR TITLE
Prompt to Create a LinkedIn Post Highlighting ServiceNow Key Features

### PR DESCRIPTION
**Pull request by Praiseto**
This prompt helps generate an engaging and professional LinkedIn post to highlight ServiceNow's key features, such as automation, custom workflows, and AI-powered insights. The post is designed to appeal to IT leaders, managers, and decision-makers, showcasing how ServiceNow can drive business efficiency and improve operations. It also includes a headline suggestion, an example of feature impact, and relevant hashtags to boost post visibility. Ideal for promoting ServiceNow’s capabilities and encouraging audience engagement.

### CODE REVIEW

**Comment by earlduque** [comment]
Hi @Praiseto, we're excited that you're already submitting, did you want to wait til Oct 1 though so it counts for Hacktoberfest? I'm not sure if PRs need to be submitted during the open October window (not just accepted). I want to make sure you get Hacktoberfest credit, so if you want to wait, let's close this one and open a new PR in October. But if you want to get this going now, just let me know, but it won't count for Hacktoberfest

**Review by earlduque — APPROVED** [review]
Looks great!

**Comment by Praiseto** [comment]
Thank You @earlduque

**Comment by earlduque** [comment]
Hello! This comment is to inform you that unfortunately, this repository, on October 3, was excluded from participation in the official Hacktoberfest event. As I investigate into why it was excluded, I would like to encourage you to participate in our other Hacktoberfest projects so that you still get completion progress for the official Hacktoberfest event.

We will count this contribution for progress made for ServiceNow rewards (make sure to check out the other eligibility requirements in the blog post), but if you want the rewards from the official event, you will need to make sure you have at least 4 Pull Requests merged into _other_ projects by the end of October. We apologize for the inconvenience and appreciate your participation regardless!

Earl

**Pull request merged**
